name: Setup Cosign
description: Install and configure cosign

runs:
  using: composite
  steps:
    - name: Install cosign
      shell: bash
      run: |
        COSIGN_VERSION="2.2.2"

        ARCH=$(uname -m)
        ARCH=${ARCH/x86_64/amd64}
        ARCH=${ARCH/aarch64/arm64}

        echo "Installing cosign for ${COSIGN_ARCH}..."
        wget -q "https://github.com/sigstore/cosign/releases/download/v${COSIGN_VERSION}/cosign-linux-${ARCH}"
        sudo mv "cosign-linux-${ARCH}" /usr/local/bin/cosign
        sudo chmod +x /usr/local/bin/cosign
        cosign version
