# Define the project configuration
products:
  - kubedoop-base
  - vector
  # devel
  - java-base
  - java-devel
  # apps
  - airflow
  - dolphinscheduler
  - go-devel
  - hadoop
  - hbase
  - hive
  - kafka
  - spark-k8s
  - superset
  - trino
  - zookeeper
  # tools
  - krb5
  - testing-tools
# If file under the path is changed, the all product will be rebuilt
global-paths:
  - .github/workflows
  - .github/scripts
  - .scripts
