name: 'Build container image'
description: 'Build container image'
inputs:
  builder_name:
    description: 'The name of the builder'
    required: false
    default: 'builder'
  tags:
    description: |
      The tags to build, the name sperated by space. e.g. "name1:version1 name1:version2 name2:version1"
      If build a tag without version, just use the name. we will build all versions of the container by 
      container metadata.json.
    required: true
  push:
    description: |
      Push the image to registry after build.
    required: false
    default: 'false'
  sign:
    description: |
      Sign the image after build.
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Build container image
      shell: bash
      env:
        BUILDER_NAME: ${{ inputs.builder_name }}
        PUSH: ${{ inputs.push }}
        SIGN: ${{ inputs.sign }}
        tags: ${{ inputs.tags }}
      run: |
        set -ex
        for tag in $tags; do
          args=(".scripts/build.sh" "product")

          if [[ $tag == *":"* ]]; then
            name=$(echo $tag | cut -d':' -f1)
            version=$(echo $tag | cut -d':' -f2)
            args+=("$name")
            if [ -n "$version" ]; then
              args+=("--product-version" "$version")
            fi
          else
            args+=("$tag")
          fi

          if [ "$PUSH" = "true" ]; then
            args+=("--push")
          fi

          if [ "$SIGN" = "true" ]; then
            args+=("--sign")
          fi

          docker exec -w /app $BUILDER_NAME "${args[@]}"

        done
