name: 'Setup buildah'
description: |
  Due to the buildah 1.33.7 of ubuntu 24.04 do not support buildah heredoc syntax,
  we build image in buildah container
  Note: buildah 1.33.0 support heredoc syntax, but it is be patched in ubuntu 24.04.
  When buildah heredoc syntax is available, we can directly build image in the runner.

inputs:
  buildah_version:
    description: 'The version of buildah to install'
    required: false
    default: 'latest'
  username:
    description: 'The username for the registry'
    required: false
  password:
    description: 'The password for the registry'
    required: false
  registry:
    description: 'The registry to login to'
    required: false
    default: 'quay.io'
  builder_name:
    description: 'The name of the builder'
    required: false
    default: 'builder'
outputs:
  buildah_version:
    description: 'The version of buildah installed'
    value: ${{ inputs.buildah_version }}
  builder_name:
    description: 'The name of the builder'
    value: ${{ inputs.builder_name }}

runs:
  using: 'composite'
  steps:
    # we need cross platform support
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Start buildah container
      shell: bash
      env:
        BUILDER_NAME: ${{ inputs.builder_name }}
        REGISTRY: ${{ inputs.registry }}
        BUILDAH_VERSION: ${{ inputs.buildah_version }}
        USERNAME: ${{ inputs.username }}
        PASSWORD: ${{ inputs.password }}
      run: |
        set -ex
        # start buildah in docker container
        docker run \
          --privileged \
          --name $BUILDER_NAME \
          -e CONTAINER_TOOL_PROVIDER=buildah \
          -e ACTIONS_ID_TOKEN_REQUEST_TOKEN=$ACTIONS_ID_TOKEN_REQUEST_TOKEN \
          -e ACTIONS_ID_TOKEN_REQUEST_URL=$ACTIONS_ID_TOKEN_REQUEST_URL \
          -e CI_SCRIPT_DEBUG=true \
          -v $(pwd):/app \
          -d \
          quay.io/buildah/stable:$BUILDAH_VERSION \
            tail -f /dev/null

        # login to quay.io
        if [ -n "$USERNAME" ] && [ -n "$PASSWORD" ]; then
          docker exec $BUILDER_NAME buildah login "$REGISTRY" --username "$USERNAME" --password "$PASSWORD"
        fi

        # install required tools
        docker exec $BUILDER_NAME sh -c "
          set -ex

          # install required tools
          dnf install -y jq 
          curl -sSfL https://github.com/sigstore/cosign/releases/latest/download/cosign-linux-amd64 -o /usr/local/bin/cosign
          chmod +x /usr/local/bin/cosign
          cosign version

          # to fix cosign publish with unauthorized error
          # https://github.com/sigstore/cosign/issues/587#issuecomment-2305367341
          # if /run/containers/0/auth.json exists, copy it to ~/.docker/config.json
          if [ -f /run/containers/0/auth.json ]; then
            mkdir -p /root/.docker/
            cp /run/containers/0/auth.json /root/.docker/config.json
          fi
        "
