name: Build Image
on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
      metadata:
        required: true
        type: string
jobs:
  build_image:
    name: Build Image
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        tag: ${{ fromJson(inputs.tag) }}
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Cache docker
      id: cache-buildx
      uses: actions/cache@v4
      with:
        path: 
          /tmp/docker-cache
        key: ${{ runner.os }}-docker-${{ github.run_id }}
        restore-keys: |
          ${{ runner.os }}-docker-
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx  
      uses: docker/setup-buildx-action@v3
    - name: Install jq
      uses: dcarbone/install-jq-action@v2.1.0
    - name: Check version
      run: |
        bash --version
        jq --version
        docker info
    - name: Build Image
      run: |
        set -ex
        TAG="${{ matrix.tag }}"
        echo "TAG from matrix: $TAG"
        
        METADATA="${{ inputs.metadata }}"
        echo "METADATA from input: $METADATA"
