name: Publish

on:
  workflow_dispatch:
  push:
    branches:
      - main


jobs:
  prepare:
    if: github.repository_owner == 'zncdatadev'
    name: Prepare Updated data
    uses: ./.github/workflows/reusable-prepare.yaml

  publish:
    name: Publish
    needs:
      - prepare
    uses: ./.github/workflows/reusable-build-publish.yaml
    with:
      registry: quay.io/zncdatadev
      cache-registry: quay.io/zncdatadev
      kubedoop_version: 0.0.0-dev
      target: ${{ matrix.target }}
      push: true
      sign: false
    secrets: inherit
    strategy:
      matrix:
        target: ${{ fromjson(needs.prepare.outputs.targets) }}
      max-parallel: 6
    if: ${{ needs.prepare.outputs.targets != '' }}
