name: Release


on:
  workflow_dispatch:
  push:
    tags:
      - '*'


# use cosign to sign with gh login, so we need pass the oidc token to the action
permissions:
  id-token: write


jobs:
  prepare:
    name: Prepare Updated data
    if: github.repository_owner == 'zncdatadev'
    uses: ./.github/workflows/reusable-prepare.yaml


  publish:
    name: Test products
    needs:
      - prepare
    uses: ./.github/workflows/reusable-build-publish.yaml
    with:
      registry: quay.io/zncdatadev
      kubedoop_version: ${{ github.ref_name}}
      targets: ${{ matrix.targets }}
      push: true
      sign: true
    strategy:
      matrix:
        targets: ${{ fromjson(needs.prepare.outputs.targets) }}
