name: Resuable Build and Publish

env:
  CI_SCRIPT_DEBUG: true
  CONTAINER_TOOL: buildah

on:
  workflow_call:
    inputs:
      registry:
        description: 'The registry to login to'
        required: false
        type: string
        default: 'quay.io/zncdatadev'
      platform_version:
        description: 'The platform version'
        required: false
        type: string
        default: '0.0.0-dev'
      builder_name:
        type: string
        description: 'The name of the builder'
        required: false
        default: 'builder'
      tags:
        description: |
          The tags to build, the name sperated by space. e.g. "name1:version1 name1:version2 name2:version1"
          If build a tag without version, just use the name. we will build all versions of the container by
          container metadata.json.
        required: true
        type: string
      push:
        description: |
          Push the image to registry after build.
        required: false
        type: boolean
        default: false
      sign:
        description: |
          Sign the image after build.
        required: false
        type: boolean
        default: false
      buildah_version:
        description: 'The version of buildah to install'
        required: false
        type: string
        default: 'latest'


jobs:
  triage:
    runs-on: ubuntu-24.04
    steps:
      - name: Show Usage
        run: |
          free -h
          df -h
          lsblk
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: show info
        run: |
          echo "Show quay username ${{ secrets.QUAY_USERNAME }}"
