name: Resuable Build and Publish

env:
  REGISTRY: quay.io/zncdatadev
  CI_SCRIPT_DEBUG: true
  CONTAINER_TOOL_PROVIDER: buildah

on:
  workflow_call:
    inputs:
      builder_name:
        type: string
        description: 'The name of the builder'
        required: false
        default: 'builder'
      tags:
        description: |
          The tags to build, the name sperated by space. e.g. "name1:version1 name1:version2 name2:version1"
          If build a tag without version, just use the name. we will build all versions of the container by 
          container metadata.json.
        required: true
        type: string
      push:
        description: |
          Push the image to registry after build.
        required: false
        type: boolean
        default: false
      sign:
        description: |
          Sign the image after build.
        required: false
        type: boolean
        default: false
      buildah_version:
        description: 'The version of buildah to install'
        required: false
        type: string
        default: 'latest'
    

jobs:
  triage:
    runs-on: ubuntu-24.04
    steps:
      - name: Show Usage
        run: |
          free -h
          df -h
          lsblk
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install buildah
        id: install_buildah
        uses: ./.github/actions/install-buildah
        with:
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
          buildah_version: ${{ inputs.buildah_version }}
          builder_name: ${{ inputs.builder_name }}
          registry: ${{ env.REGISTRY }}
      - name: Build Images
        uses: ./.github/actions/build-containers
        with:
          tags: ${{ inputs.tags }}
          sign: ${{ inputs.sign }}
          push: ${{ inputs.push }}
          builder_name: ${{ inputs.builder_name }}
