name: test


on:
  pull_request:
    branches:
      - main


jobs:
  prepare:
    name: Prepare Updated data
    uses: ./.github/workflows/reusable-prepare.yaml


  test:
    name: Test
    needs:
      - prepare
    uses: ./.github/workflows/reusable-build-publish.yaml
    with:
      registry: quay.io/zncdatadev
      targets: ${{ matrix.targets }}
    strategy:
      matrix:
        targets: ${{ fromjson(needs.prepare.outputs.targets) }}
